import { type NextPage } from "next";
import Head from "next/head";
import { withRedirects } from "~/server/api/firebase/withRedirects";
import { signOut } from "~/utils/firebase/auth";
import { useRouter } from "next/router";
import { useWallet } from "@solana/wallet-adapter-react";

const Home: NextPage = () => {
  // eslint-disable-next-line @typescript-eslint/unbound-method
  const { disconnect } = useWallet();
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button
        onClick={() =>
          void signOut({
            onSuccess: async () => {
              await disconnect();
              router.reload();
            },
          })
        }
      >
        Cerrar sesion
      </button>
    </>
  );
};

export const getServerSideProps = withRedirects({
  onAuthFailure: () => ({ destination: "/login", permanent: false }),
  onAuthSuccess: ({ user }) => {
    return user.publicKey
      ? undefined
      : { destination: "/wallet", permanent: false };
  },
});

export default Home;
